### PR TITLE
RFC: Release and Versioning Plan

### PR DESCRIPTION
**Pull request by thermokarst**
This is a placeholder PR right now for the release and versioning discussion surrounding QIIME 2. This document still needs to be updated to reflect discussion points that occurred outside of GH.

### CODE REVIEW

**Comment by ebolyen** [comment]
To add to this, I think it is worth going over [PEP 440](https://www.python.org/dev/peps/pep-0440/) which gives a standard for versioning. In particular I want to point out the [Version Epoch](https://www.python.org/dev/peps/pep-0440/#version-epochs) syntax which appears to be [supported by conda](https://github.com/conda/conda/issues/2824). This was created to deal with almost our exact situation (versioning scheme changes). We could imagine QIIME 2 just represents an epoch like `2!<any PEP 440 scheme here>` which will allow conda and pip to resolve dependencies correctly.

**Comment by ebolyen** [comment]
Date based versions are also explicitly supported by this PEP which may be significantly more meaningful for our user-base especially if we do train-style releases as described in this RFC.

**Comment by ebolyen** [comment]
(Sorry for the continued comment chain, I know everyone is still on vacation, but I was researching [versioneer](https://github.com/warner/python-versioneer) and had to throw this in)

Here is a potential versioning scheme (PEP 440 - normal form) tracking our first LTS release:

`2!2017.06.0rc0` (dev release)
`2!2017.06.0rc1` (dev release)
`2!2017.06.0`    (standard release)
`2!2017.06.0.1`  (standard release - bug fix)
`2!2017.06.0.2`  (standard release - bug fix)
`2!2017.06.1`    (LTS release)
`2!2017.06.1.1`  (LTS release - bug fix)

This also has the advantage of us being able to promote any release to an LTS (if ever needed, by flipping the `<date>.0` to `<date>.1`). This is necessary as PEP 440 unfortunately does not have any mechanism for supplying `LTS` in the version tag.

With [versioneer](https://github.com/warner/python-versioneer), specific git offsets can be calculated as we develop:

`2!2017.09.0+2.g1076c97.dirty`

The above stands for a dev version on a local machine (`+`) that is 2 commits ahead (`2.g1076c97`) of the last release (`2!2017.09.0`) with uncomitted changes (`.dirty`). This would automatically be calculated from `git` and set as the specific `__version__` dynamically.

**Comment by thermokarst** [comment]
Tossing this here for reference: https://docs.djangoproject.com/en/1.9/internals/release-process/

**Comment by thermokarst** [comment]
This PR is back in my court for now: it needs to be revised to reflect changes introduced in #1 & #3. I will apply the `needs-guide` tag to indicate when I am done with that process.

**Comment by thermokarst** [comment]
Closing this for now, we can revisit if we pull `rfcs` back into the org.

**Pull request closed without merging**
